### ISSUE TITLE
Excuse me, could you tell me how to connect to the hotspot remotely with ssh?

### ISSUE THREAD

**Issue by Fang-Li** [FezzFest/check-helium-bannedlist#1]
_How to extract your public key:_

**SSH to your hotspot** _and login to the remote_console with sudo docker exec -it miner miner remote_console_

**Comment by FezzFest** [comment]
This is not possible on all hotspots. Luckily, there's now a much easier way to check whether you're affected: type in your hotspot address on https://blacklist.longap.community/ or check the address and/or name on [@ricopt5's list](https://gist.githubusercontent.com/ricopt5/d7a8fd85de6dc18cbb72ab74b92d0223/raw/640f84a05c6bdbef2133e4638682646006175478/helium_blacklist.csv).

**Comment by dannypm** [comment]
Possible to describe the procedure?
Since this list will be enlarged and ppl would need to constantly check the status of their hotspots.
